void INTswap(int *a, int *b);
void CHARswap(char *a, char *b);
void FLOATswap(float *a, float *b);
void INTBubbleSort(int v[], int n);
void CHARBubbleSort(char v[], int n);
void FLOATBubbleSort(float v[], int n);
void INTInsertionSort(int v[], int n);
void CHARInsertionSort(char v[], int n);
void FLOATInsertionSort(float v[], int n);
void INTSelectionSort(int v[], int n);
void CHARSelectionSort(char v[], int n);
void FLOATSelectionSort(float v[], int n);
void INTmerge(int *l1, int *l2,int n,int *l3);
void INTMergeSort(int *l, int n);
void CHARmerge(char *l1, char *l2,int n,char *l3);
void CHARMergeSort(char *l, int n);
void FLOATmerge(float *l1, float *l2,int n,float *l3);
void FLOATMergeSort(float *l, int n);
int INTpartition(int v[],int L, int R);
void INTQuickSort(int v[], int L, int R);
int CHARpartition(char v[],int L, int R);
void CHARQuickSort(char v[], int L, int R);
int FLOATpartition(float v[],int L, int R);
void FLOATQuickSort(float v[], int L, int R);
